[phases.setup]
nixPkgs = ["...", "python311Packages.supervisor"]

[phases.build]
cmds = [
    "mkdir -p /etc/supervisor/conf.d/",
    "cp /assets/worker-*.conf /etc/supervisor/conf.d/",
    "cp /assets/supervisord.conf /etc/supervisord.conf",
    "chmod +x /assets/extra.sh",
    "php artisan migrate --force",
    "php artisan optimize:clear",
    "...",
]

[start]
cmds = ["/assets/exra.sh", "..."]

[staticAssets]
"extra.sh" = '''
#!/bin/bash

# Enable OPcache (does this even work?)
PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}')
# Enable opcache by adding to the bottom of the php.ini
echo opcache.memory_consumption=256 >> "$PHP_INI_PATH"
echo opcache.interned_strings_buffer=64 >> "$PHP_INI_PATH"
echo opcache.max_accelerated_files=32531 >> "$PHP_INI_PATH"
echo opcache.validate_timestamps=0 >> "$PHP_INI_PATH"
echo opcache.enable_cli=1 >> "$PHP_INI_PATH"

# Start supervisor
supervisord -c /etc/supervisord.conf -n
'''

"supervisord.conf" = '''
[unix_http_server]
file=/assets/supervisor.sock

[supervisord]
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/assets/supervisord.pid
nodaemon=false
silent=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///assets/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
'''

"worker-laravel.conf" = '''
# [program:worker-laravel]
# process_name=%(program_name)s_%(process_num)02d
# command=bash -c 'exec php /app/artisan queue:work --sleep=3 --tries=3 --max-time=3600'
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# numprocs=12
# startsecs=0
# stopwaitsecs=3600
# stdout_logfile=/var/log/worker-laravel.log
# stderr_logfile=/var/log/worker-laravel.log
[program:laravel-reverb]
process_name=%(program_name)s
command=php /app/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
minfds=10000
redirect_stderr=true
stdout_logfile=/app/storage/logs/reverb.log
stopwaitsecs=3600
stdout_logfile_maxbytes=5MB
'''