[phases.setup]
nixPkgs = ["...", "python311Packages.supervisor"]

[phases.build]
cmds = [
    "chmod +x /assets/extra.sh",
    "php artisan migrate --force",
    "php artisan optimize:clear",
    "...",
]

[start]
cmds = ["/assets/exra.sh", "..."]

[staticAssets]
"extra.sh" = '''
#!/bin/bash

PHP_INI_PATH=$(php -i | grep '/php.ini' | awk '{print $6}')
# Enable opcache by adding to the bottom of the php.ini
echo opcache.memory_consumption=256 >> "$PHP_INI_PATH"
echo opcache.interned_strings_buffer=64 >> "$PHP_INI_PATH"
echo opcache.max_accelerated_files=32531 >> "$PHP_INI_PATH"
echo opcache.validate_timestamps=0 >> "$PHP_INI_PATH"
echo opcache.enable_cli=1 >> "$PHP_INI_PATH"
'''
